version: '3'

services: 
  db:
    image: postgres
    restart: always
    environment: 
      POSTGRES_PASSWORD: passwdRails
    volumes: 
      - ./tmp/db:/var/lib/postgresql/data
    ports: 
      - "5432:5432"

  api:
    build: 
      dockerfile: ./docker/rails.dockerfile
      context: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    image: lucas/api
    volumes: 
      - ./:/myapp
    ports: 
      - "3000:3000"
    depends_on: 
      - db